### ISSUE TITLE
Rename default branch to 'main'

### ISSUE THREAD

**Issue by Normo** [hifis-net/ansible-role-ssh-keys#1]

**Comment by tobiashuste** [comment]
Is there something we need to consider before we can rename the default brancht to `main`? Currently our settings already expect the default branch to be called `main`.

**Comment by Normo** [comment]
There will probably be an issue with Ansible Galaxy - see https://github.com/ansible/galaxy/issues/2535#issuecomment-783335049
This can be solved by removing and re-import the role if I remember correctly.

**Comment by Normo** [comment]
Switched default branch to `main`
