### ISSUE TITLE
Add a contribution guide

### ISSUE THREAD

**Issue by tobiashuste** [hifis-net/ansible-role-ssh-keys#16]
Since we have decided to use GitHub due to the fact that we want to invite more external contributors we should also make sure to have the relevant information in place. This is why I suggest to add a Contribution guide to all our Ansible projects.

I found a nice template here: https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md

\cc @Normo @christianhueserhzdr

**Comment by christianhueserhzdr** [comment]
Dear Tobias @tobiashuste, a CONTRIBUTING guide is a good idea. I wrote a [CONTRIBUTING guide](https://gitlab.hzdr.de/hifis/overall/surveys/hifis-surveyval/-/blob/main/CONTRIBUTING.md) in a different project and would like to propose something along these lines.
