### ISSUE TITLE
Replacement for Centos 8

### ISSUE THREAD

**Issue by tobiashuste** [hifis-net/ansible-role-ssh-keys#18]
Since Centos 8 is EOL since end of 2021 we probably need a replacement for our Centos 8 image we use in Molecule.

Geerlingguy provides an image for Rocky Linux 8 - https://hub.docker.com/r/geerlingguy/docker-rockylinux8-ansible. This way we could switch to using the geerlingguy images to be consistent with the other projects.

Probably testing for RockyLinux would also mean compatibility with AlmaLinux. What do you think, @Normo?

**Comment by Normo** [comment]
Sounds reasonable to me! :+1:
