### ISSUE TITLE
Rename project to ansible-role-ssh-keys

### ISSUE THREAD

**Issue by tobiashuste** [hifis-net/ansible-role-ssh-keys#4]
To be in line with the other projects I suggest to rename it to `ansible-role-ssh-keys`. Any objections?

@Normo @christianhueserhzdr

**Comment by christianhueserhzdr** [comment]
That's fine. Thanks.

**Comment by Normo** [comment]
I'm okay with that. Although I don't know yet if this leads to any issues with the Ansible Galaxy import.

**Comment by tobiashuste** [comment]
Renamed the project to `ansible-role-ssh-keys`. Will update links now that might still be part of the project.
